using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace CLFeedPull.NetCore
{
    /// <summary>
    /// This extention of the AutoGenerated base class allows you to automatically have the "Ext_" fields in a Cloverleaf document
    /// available via the class interface.
    /// </summary>
    partial class SchemaBase
    {
        [BsonIgnore]
        private BsonDocument _ExtFields;
        [BsonExtraElements]
        public BsonDocument ExtFields
        {
            get { return _ExtFields = _ExtFields ?? new BsonDocument(); }
            set { _ExtFields = value; }
        }
    }


    /// <summary>
    /// Typed response wrapper for pulling data from Cloverleaf feeds.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public class FeedResponse<T>
    {
        [BsonIgnore]
        private T[] _Entities;
        public T[] Entities
        {
            get { return _Entities = _Entities ?? new T[0]; }
            set { _Entities = value; }
        }

        [BsonIgnoreIfDefault]
        public string NextSince { get; set; }

        [BsonIgnoreIfDefault]
        public int EstMoreRecords { get; set; }

        [BsonIgnoreIfDefault]
        public long EstMoreBytes { get; set; }
    }
}